# Generated by Django 5.0.4 on 2024-04-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='nome',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='rg',
            new_name='id_card',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='rua',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='photo_perfil',
            new_name='photo_profile',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='bairro',
            new_name='zone',
        ),
    ]
